spring.application.name=elektrikli_arac_sarj_sistemi

# Sunucu Portu
server.port=8080

# PostgreSQL (Docker) Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/nafi_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


app:
  jwt:
    secret: "bu-cok-uzun-ve-gizli-bir-anahtar-olmali-en-az-256-bit-uzunlukta-degistirilmeli"
    expiration-ms: 86400000  # 24 saat